name: WolvesVSPigs
main: io.github.fourohfour.wolvesvspigs.WolvesVSPigs
version: 0.3.6
commands:
  wvpa:
    description: Admin commands for the Wolves VS Pigs Plugin
    usage: /wvpa [command ex. help]
    permission: WolvesVSPigs.admin
    permission-message: You are not a WVP admin.