name: WolvesVSPigs
author: FourOhFour
main: io.github.fourohfour.wolvesvspigs.WolvesVSPigs
version: 1.0.0
commands:
  wvpa:
    description: Admin commands for the Wolves VS Pigs Plugin
    usage: "/wvpa [command ex. help] <parameters if needed>"
    permission: WolvesVSPigs.admin
    permission-message: You do not have permission to perform WVP Admin commands.
  wvp:
    description: Basic commands for the Wolves VS Pigs Plugin
    usage: "/wvp [command ex. help] <parameters if needed>"
    permission: WolvesVSPigs.basic
    permission-message: You do not have permission to perform WVP commands.
  wvpd:
    description: Developer commands for WVP
    usage: "/wvpd [command ex. help] <parameters if needed>"
    permission: WolvesVSPigs.dev
    permission-message: You do not have permission to perform WVP Developer commands.